/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evolution;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import worldObject.Agent;

/**
 *
 * @author Link
 */
public class MainJFrame extends javax.swing.JFrame implements Runnable {

    NeuralNetPanel neuralPanel;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setSize(1200, 900);
        jPanel_NeuralNet.setVisible(true);
        this.jInternalFrame_controlPanel.setVisible(false);
        (new Thread(this)).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel_simulation = new EvolutionWorld();
        jInternalFrame_controlPanel = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_NeuralNet = new NeuralNetPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox_agent_wireframe = new javax.swing.JCheckBox();
        jCheckBox_agent_indicators = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox_agent_showDebug = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox_Env_showPlants = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jCheckBox_env_debug = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_restart = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu_agent_targetHighestGen = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem_sensor = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem_debugInfo = new javax.swing.JCheckBoxMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jSplitPane2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSplitPane2MouseDragged(evt);
            }
        });
        jSplitPane2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSplitPane2PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel_simulationLayout = new javax.swing.GroupLayout(jPanel_simulation);
        jPanel_simulation.setLayout(jPanel_simulationLayout);
        jPanel_simulationLayout.setHorizontalGroup(
            jPanel_simulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel_simulationLayout.setVerticalGroup(
            jPanel_simulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        jSplitPane2.setLeftComponent(jPanel_simulation);

        jInternalFrame_controlPanel.setClosable(true);
        jInternalFrame_controlPanel.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jInternalFrame_controlPanel.setTitle("Control Panel");
        jInternalFrame_controlPanel.setVisible(true);
        jInternalFrame_controlPanel.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame_controlPanelInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame_controlPanelInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel_NeuralNetLayout = new javax.swing.GroupLayout(jPanel_NeuralNet);
        jPanel_NeuralNet.setLayout(jPanel_NeuralNetLayout);
        jPanel_NeuralNetLayout.setHorizontalGroup(
            jPanel_NeuralNetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel_NeuralNetLayout.setVerticalGroup(
            jPanel_NeuralNetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Neural Net", jPanel_NeuralNet);

        jLabel1.setText("Sensors");

        jCheckBox_agent_wireframe.setText("Show Wire Frame");
        jCheckBox_agent_wireframe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_agent_wireframeActionPerformed(evt);
            }
        });

        jCheckBox_agent_indicators.setText("Show Indicators");
        jCheckBox_agent_indicators.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_agent_indicatorsActionPerformed(evt);
            }
        });

        jLabel2.setText("Auto Target");

        jButton1.setText("Random");

        jButton2.setText("Highest Gen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCheckBox_agent_showDebug.setText("Show Debug");
        jCheckBox_agent_showDebug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_agent_showDebugActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCheckBox_agent_wireframe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addComponent(jCheckBox_agent_indicators)
                                .addComponent(jLabel2)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jCheckBox_agent_showDebug))
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_agent_wireframe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_agent_indicators)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(29, 29, 29)
                .addComponent(jCheckBox_agent_showDebug)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 205, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agent", jPanel2);

        jCheckBox_Env_showPlants.setSelected(true);
        jCheckBox_Env_showPlants.setText("Show Plants");
        jCheckBox_Env_showPlants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_Env_showPlantsActionPerformed(evt);
            }
        });

        jButton3.setText("Restart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jCheckBox_env_debug.setText("Show Debug");
        jCheckBox_env_debug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_env_debugActionPerformed(evt);
            }
        });

        jButton4.setText("Next Generation");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox_env_debug)
                    .addComponent(jCheckBox_Env_showPlants)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jCheckBox_Env_showPlants)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox_env_debug)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Environment", jPanel3);

        jScrollPane1.setViewportView(jTabbedPane1);

        javax.swing.GroupLayout jInternalFrame_controlPanelLayout = new javax.swing.GroupLayout(jInternalFrame_controlPanel.getContentPane());
        jInternalFrame_controlPanel.getContentPane().setLayout(jInternalFrame_controlPanelLayout);
        jInternalFrame_controlPanelLayout.setHorizontalGroup(
            jInternalFrame_controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        jInternalFrame_controlPanelLayout.setVerticalGroup(
            jInternalFrame_controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jSplitPane2.setRightComponent(jInternalFrame_controlPanel);

        jMenu1.setText("File");

        jMenuItem_restart.setText("Restart");
        jMenuItem_restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_restartActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_restart);

        jMenuItem4.setText("Close File");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuItem6.setText("Show Control Panel");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu_agent_targetHighestGen.setText("Agent");

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jMenuItem10.setText("Highest Generation");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu_agent_targetHighestGen.add(jMenuItem10);

        jMenuBar1.add(jMenu_agent_targetHighestGen);

        jMenu4.setText("Debug");

        jCheckBoxMenuItem_sensor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        jCheckBoxMenuItem_sensor.setText("Show Sensors");
        jCheckBoxMenuItem_sensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem_sensorActionPerformed(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem_sensor);

        jCheckBoxMenuItem_debugInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        jCheckBoxMenuItem_debugInfo.setText("Debug Info");
        jCheckBoxMenuItem_debugInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem_debugInfoActionPerformed(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem_debugInfo);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItem_sensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem_sensorActionPerformed
        Debug.drawFOV = this.jCheckBoxMenuItem_sensor.getState();
    }//GEN-LAST:event_jCheckBoxMenuItem_sensorActionPerformed

    private void jCheckBoxMenuItem_debugInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem_debugInfoActionPerformed
        Debug.envDebug = this.jCheckBoxMenuItem_debugInfo.getState();
    }//GEN-LAST:event_jCheckBoxMenuItem_debugInfoActionPerformed

    private void jMenuItem_restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_restartActionPerformed
        ((EvolutionWorld) jPanel_simulation).reset();
    }//GEN-LAST:event_jMenuItem_restartActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ((EvolutionWorld) this.jPanel_simulation).close();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        ((EvolutionWorld) this.jPanel_simulation).requestTargetHighestScore();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.jInternalFrame_controlPanel.setVisible(true);
        jSplitPane2.setDividerLocation(getWidth() - 310);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jInternalFrame_controlPanelInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame_controlPanelInternalFrameClosing
        this.jInternalFrame_controlPanel.setVisible(false);
    }//GEN-LAST:event_jInternalFrame_controlPanelInternalFrameClosing

    private void jInternalFrame_controlPanelInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame_controlPanelInternalFrameClosed

    }//GEN-LAST:event_jInternalFrame_controlPanelInternalFrameClosed

    private void jSplitPane2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSplitPane2MouseDragged

    }//GEN-LAST:event_jSplitPane2MouseDragged

    private void jSplitPane2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSplitPane2PropertyChange

    }//GEN-LAST:event_jSplitPane2PropertyChange

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        jInternalFrame_controlPanel.setVisible(false);
    }//GEN-LAST:event_formComponentResized

    private void jCheckBox_Env_showPlantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_Env_showPlantsActionPerformed
        Debug.drawFood = jCheckBox_Env_showPlants.isSelected();
    }//GEN-LAST:event_jCheckBox_Env_showPlantsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ((EvolutionWorld) jPanel_simulation).reset();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox_env_debugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_env_debugActionPerformed
        Debug.envDebug = jCheckBox_env_debug.isSelected();
    }//GEN-LAST:event_jCheckBox_env_debugActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ((EvolutionWorld) this.jPanel_simulation).startNextGeneration();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox_agent_showDebugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_agent_showDebugActionPerformed
        Debug.agentDebug = jCheckBox_agent_showDebug.isSelected();
    }//GEN-LAST:event_jCheckBox_agent_showDebugActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ((EvolutionWorld) this.jPanel_simulation).requestTargetHighestScore();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox_agent_indicatorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_agent_indicatorsActionPerformed
        Debug.drawFOV = jCheckBox_agent_indicators.isSelected();
    }//GEN-LAST:event_jCheckBox_agent_indicatorsActionPerformed

    private void jCheckBox_agent_wireframeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_agent_wireframeActionPerformed
        Debug.drawFOVWireFrame = jCheckBox_agent_wireframe.isSelected();
    }//GEN-LAST:event_jCheckBox_agent_wireframeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem_debugInfo;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem_sensor;
    private javax.swing.JCheckBox jCheckBox_Env_showPlants;
    private javax.swing.JCheckBox jCheckBox_agent_indicators;
    private javax.swing.JCheckBox jCheckBox_agent_showDebug;
    private javax.swing.JCheckBox jCheckBox_agent_wireframe;
    private javax.swing.JCheckBox jCheckBox_env_debug;
    private javax.swing.JInternalFrame jInternalFrame_controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem_restart;
    private javax.swing.JMenu jMenu_agent_targetHighestGen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_NeuralNet;
    private javax.swing.JPanel jPanel_simulation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {

            try {
                Thread.sleep(1000 / 25);
                Agent a = ((EvolutionWorld) jPanel_simulation).getTargetAgent();
                if (a != null) {
                    ((NeuralNetPanel) jPanel_NeuralNet).setNeuralNetwork(a.neuralNet);
                } else {
                    ((NeuralNetPanel) jPanel_NeuralNet).setNeuralNetwork(null);
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

}
